version: "3.9"

services:
  chatbot-api:
    build: .
    container_name: chatbot_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:7.0
    container_name: chatbot_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: chatbot_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
